---
title: "Assignment"
description: To be a Visual Detective
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

The assignments require you to put the concepts, methods and techniques you had learned in class to solve real world problem using visual analytics techniques.  Students should also use the assignments to gain hands-on experience on using R data visualisation and data analysis packages to complete the assignment.

## The Case

The assignment topics are based on [VAST Challenge 2021](https://vast-challenge.github.io/2021/).  You are required to choose one of the challenge topic provided below and work out the solution.

In the roughly twenty years that Tethys-based GAStech has been operating a natural gas production site in the island country of Kronos, it has produced remarkable profits and developed strong relationships with the government of Kronos. However, GAStech has not been as successful in demonstrating environmental stewardship.

In January, 2014, the leaders of GAStech are celebrating their new-found fortune as a result of the initial public offering of their very successful company. In the midst of this celebration, several employees of GAStech go missing. An organization known as the Protectors of Kronos (POK) is suspected in the disappearance, but things may not be what they seem.

As an expert in visual analytics, you are called in to help law enforcement from Kronos and Tethys.

### Mini-Challenge 1

Mini-Challenge 1 looks at the relationships and conditions that led up to the kidnapping. As an analyst, you have a set of current and historical news reports at your disposal, as well as resumes of numerous GAStech employees and email headers from two weeks of internal GAStech company email. Can you identify the complex relationships among all of these people and organizations?

Please visit [VAST Challenge 2021: Mini-Challenge 1](https://vast-challenge.github.io/2021/MC1.html) for more information and to download the data.

### Mini-Challenge 2

Mini-Challenge 2 asks you to analyze movement and tracking data. GAStech provides many of their employees with company cars for their personal and professional use, but unbeknownst to the employees, the cars are equipped with GPS tracking devices. You are given tracking data for the two weeks leading up to the disappearance, as well as credit card transactions and loyalty card usage data. From this data, can you identify anomalies and suspicious behaviors? Can you identify which people use which credit and loyalty cards?

Please visit [VAST Challenge 2021: Mini-Challenge 2](https://vast-challenge.github.io/2021/MC2.html) for more information and to download the data.

### Mini-Challenge 3

Mini-Challenge 3 poses a social media and text analysis challenge. You will be given a collection of microblogs and emergency calls from the days surrounding the disappearance. Can evaluate the changing levels of risk to the public and recommend actions?

Please visit [VAST Challenge 2021: Mini-Challenge 3](https://vast-challenge.github.io/2021/MC3.html) for more information and to download the data.

## The Task 

- Conducting literature review on how the analysis were performed before.  The focus should be on identifying gaps whereby interactive visual analytics approach can be used to enhance user experience on using the analysis techniques. 
- Extracting, wrangling and preparing the input data required to perform the analysis.  The focus should be on exploring appropriate tidyverse methods
- Using appropriate **visually driven data analysis techniques** to answer the questions asked.

## Submission Instructions 

- This is an individual assignment. You are required to work on the assignment and prepare submission individually. 

* The assignment report must be written by using R Markdown.  It can be in either [Distill](https://rstudio.github.io/distill/) or [blogdown](https://github.com/rstudio/blogdown) format. You are required to publish the assignment report on [Netlify](https://www.netlify.com/) and provide the link on the assignment submission page on elearn. 
- Upload the assignment report and data onto your individual Github repository and provide the link on the assignment submission page on eLearn.
 
## Submission date 
 
Your completed assignment is due on ~~18th July 2021~~ **25th July 2021 (Sunday), mid-night 11:59pm**.

## Reference
### Past Assignment Page

- [AY2015-16 Term 3](https://wiki.smu.edu.sg/1617t3isss608g1/Assignment_Dropbox AY2016-17 Term 3 Assignment)
- [AY2017-18 Term 3 Assignment](https://wiki.smu.edu.sg/1718t3isss608/Assignments)
- [AY2018-19 Term 1 Assignment](https://wiki.smu.edu.sg/18191isss608g1/Assignment)
- [AY2018-2019 Term 3](https://wiki.smu.edu.sg/1819t3isss608/Assignment_Dropbox_G1)
- [AY2019-2020 Term 2](https://wiki.smu.edu.sg/1920t2isss608/Assignment_Dropbox)
- [AY2020-2021 Term 2](https://wiki.smu.edu.sg/2021t2isss608/Assignment)


### Specially mentioned
- [Dino Holmes Series](https://wiki.smu.edu.sg/1617t1ISSS608g1/ISSS608_2016-17_T1_Assign3_Ong_Han_Ying)
- [Mystery at the Wildlife Preserve](https://wiki.smu.edu.sg/1617t3isss608g1/ISSS608_2016-17_T3_Assign_GUAN_YIFEI)
- [VAST Challenge 2017 MC3](https://wiki.smu.edu.sg/1617t3isss608g1/ISSS608_2016-17_T3_Assign_ZHANG_YANRONG)
- [Sickness in SmartPolis](https://wiki.smu.edu.sg/1718t1isss608g1/ISSS608_2017-18_T1_Assign_RACHEL_TONG)
- [Suspense at the Wildlife Preserve](https://wiki.smu.edu.sg/1718t3isss608/ISSS608_2017-18_T3_Assign_Tan_Yong_Ying)
- [Unmask Air Pollution in Sofia City](https://wiki.smu.edu.sg/18191isss608g1/ISSS608_2018-19_T1_Assign_Pu_Yiran)

## Assignment Submission
### G1

- AHMAD FADY GANIS
    - [Assignment write-up on Netlify](https://fadyganis-vast2.netlify.app/)

- ARCHIE QUIAMBAO DOLIT
    - [Assignment write-up on Netlify](https://adolit-vaa.netlify.app/posts/2021-07-18-assignment/)

- ARYAH UMRALKAR CHOPRA
    - [Assignment write-up on Netlify](https://arychopra-vc.netlify.app/)

- CHEN YUXI
    - [Assignment write-up on Netlify](https://yuxich.netlify.app/posts/2021-06-21-assignment/)

- CONNIE XIA YI JING
    - [Assignment write-up on Netlify](https://connie-xia.netlify.app/posts/2021-07-25-assignment-1/)

- HONG YUN TING
    - [Assignment write-up on Netlify](https://hongyunting.netlify.app/posts/2021-07-20-assignment-mc2/)

- HUANG LINYA
    - [Assignment write-up on Netlify](https://linyah-assignment.netlify.app/)

- HUANG SHAN
    - [Assignment write-up on Netlify](https://hs-visual.netlify.app/posts/2021-07-25-datavizblog/)

- JOVINKA HARTANTO
    - [Assignment write-up on Netlify](https://mc2jovinka.netlify.app/)

- KELLY KOH KIA WOON
    - Assignment write-up on Netlify: [Part 1](https://kellykkw.netlify.app/posts/2021-07-25-individual-assignment-part-1/), [Part 2](https://kellykkw.netlify.app/posts/2021-07-25-individual-assignment-part-3/), and [Part 3](https://kellykkw.netlify.app/posts/2021-07-25-individual-assignment-part-3/) 

- KEVIN MAGIC RIALUBIN SUNGA
    - [Assignment write-up on Netlify](https://kevinsunga.netlify.app/posts/2021-07-11-assignment/)

- LI SHUXIAN
    - [Assignment write-up on Netlify](https://gracious-bhaskara-0d9bfe.netlify.app/posts/2021-07-14-vast-2021-mc-3/)

- LI YUHONG
    - [Assignment write-up on Netlify](https://yuhongliblog.netlify.app/posts/2021-07-05-assignment/)

- LI YUMENG
    - [Assignment write-up on Netlify](https://nicetry.netlify.app/posts/individual%20assignment/)

- LIAN YINGZHEN JOANNA
    - [Assignment write-up on Netlify](https://isss608vizanalysis.netlify.app/posts/2021-07-18-assignment-mc2/)

- LIANG YINGFANG
    - [Assignment write-up on Netlify](https://isss608blog.netlify.app/posts/vast%20challenge%202021%20mc2/)

- LIM JIAHUI
    - [Assignment write-up on Netlify](https://limjiahui.netlify.app/posts/2021-07-07-viz-assignment/)

- LIM JIN RU
    - [Assignment write-up on Netlify](https://lim-jin-ru-assignment-mini-challenge1.netlify.app/posts/2021-07-23-vast-challenge-2021-mini-challenge-1/)

- LIM YONG KAI
    - [Assignment write-up on Netlify](https://limyongkai.netlify.app/posts/2021-07-23-vastmc2part1/)

- LIU YANGGUANG
    - [Assignment write-up on Netlify](https://ygliu.netlify.app/posts/2021-07-23-vast-challenge-2021-mc2/)

- LOH YUN JIA STELLA
    - [Assignment write-up on Netlify](https://isss608-assignment.netlify.app/index.html)

- LUO HAOYU
    - [Assignment write-up on Netlify](https://r4dsa-lhy.netlify.app/)

- MANMIT SINGH S/O NARMAL SINGH
    - [Assignment write-up on Netlify](https://gallant-hawking-d63d10.netlify.app/posts/2021-07-16-third-time-a-charm/)

- MAYURAPRIYANN ARULMOZHI BASKARAN
    - [Assignment write-up on Netlify](https://mayur-dataviz1.netlify.app/posts/2021-07-25-assignment-vast-challenge-mc2/)

- NG DING XUAN ARNOLD
    - [Assignment write-up on Netlify](https://arnoldndx.netlify.app/posts/2021-07-16-assignment/)

- NG YEN NGEE
    - [Assignment write-up on Netlify](https://yenngee-dataviz.netlify.app/post/2021-07-16-mc1-findings/)

- NIKITHA BANDA
    - [Assignment write-up on Netlify](https://vast-challenge.netlify.app/)

- NURULASYIQAH BINTE MOHAMMAD TAHA
    - [Assignment write-up on Netlify](https://vasq.netlify.app/posts/2021-07-13-assignment/)

- OH YAO WEI AARON
    - [Assignment write-up on Netlify](https://aaronoh743.netlify.app/posts/2021-07-07-assignment-1/)

- ONG CHEE HONG
    - [Assignment write-up on Netlify](https://chvastassignment.netlify.app/)

- RHODA TONG MIN TING
    - [Assignment write-up on Netlify](https://mttong.netlify.app/posts/2021-07-25-my-assignment/)

- RYAN CHAN WEIYAO
    - [Assignment write-up on Netlify](https://ryan-chan.netlify.app/posts/2021-07-12-vast-challenge-mini-challenge-3/)

- SHEN XIAOJING
    - [Assignment write-up on Netlify](https://xiaojingshen.netlify.app/posts/assignment/)

- SYED AHMAD ZAKI BIN SYED SAKAF AL-ATTAS
    - Assignment write-up on Netlify: [Part 1](https://syedahmadzakidataviz.netlify.app/posts/2021-07-26-assignment-part-1/), [Part 2](https://syedahmadzakidataviz.netlify.app/posts/2021-07-26-assignment-part-2/) and [Part 3](https://syedahmadzakidataviz.netlify.app/posts/2021-07-26-assignment-part-3/)

- TAN CHEE SENG DAVMES
    - [Assignment write-up on Netlify](https://dtcs.netlify.app/posts/2021-07-13-assignment-1/)

- TAN CHOO THYE
    - [Assignment write-up on Netlify](https://funplaywdata06.netlify.app/posts/2021-06-28-assignment-vast-challenge-2021/)

- TAN KAR YEE
    - [Assignment write-up on Netlify](https://isss608-kytan-vast2021.netlify.app/posts/2021-07-07-mc3/)

- WANG QINYU
    - [Assignment write-up on Netlify](https://wangqy075.netlify.app/posts/2021-07-14-assignment/)

- XU DAN
    - [Assignment write-up on Netlify](https://visualsaturday.netlify.app/)

- YAN RUIYUN
    - [Assignment write-up on Netlify](https://optimistic-ritchie-9926db.netlify.app/)

- YANG XU
    - [Assignment write-up on Netlify](https://visualdataviz.netlify.app/posts/2021-07-17-assignment/)

- YEO CHIA GUAN ANDY
    - Assignment write-up on Netlify [Part 1](https://andyyeodataviz.netlify.app/posts/2021-07-27-isss608-assignment-1-part-1/) and [Part 2](https://andyyeodataviz.netlify.app/posts/2021-07-27-isss608-assignment-1-part-2/)

- YEO DING RUN
    - [Assignment write-up on Netlify](https://yeodingrun-vastchallenge2021.netlify.app/)

- YU YAXIN
    - [Assignment write-up on Netlify](https://determined-jepsen-0f6bf9.netlify.app/)

- ZHANG YING
    - [Assignment write-up on Netlify](https://alicia-zhang.netlify.app/posts/2021-07-11-dataviz-assignment/)

- ZHONG LINLI
    - [Assignment write-up on Netlify](https://linlizhong.netlify.app/)

### G2

- BAI YINING
    - [Assignment write-up on Netlify](https://yiningmakeover1.netlify.app/posts/2021-07-13-assignment/)

- DONG FANG
    - [Assignment write-up on Netlify](https://dongfang-regina.netlify.app/posts/2021-07-17-assignvastchallenge/)
    
- JESSICA TAN SOO CHENG
    - [Assignment write-up on Netlify](https://gracious-lumiere-bd59cb.netlify.app/methodology.html)
    
- JOYCE WOON SHI HUI
    - [Assignment write-up on Netlify](https://jwdatavizassignment.netlify.app/posts/welcome/)
    
- LANG SHUANG
    - [Assignment write-up on Netlify]()
    
- LEE SULING
    - [Assignment write-up on Netlify](https://datavisvast2021.netlify.app/insights.html)
    
- LI NAN
    - [Assignment write-up on Netlify](https://dataviz2linan.netlify.app/posts/2021-07-13-assignment/)
    
- LI YUETING
    - [Assignment write-up on Netlify](https://yuetingassignment.netlify.app/)
    
- LI ZHEN
    - [Assignment write-up on Netlify](https://visualizationzhen.netlify.app/posts/2021-07-05-aliba-crime-analysis/)  
    
- LIN PEIRONG
    - [Assignment write-up on Netlify](https://perry-dataviz.netlify.app/posts/2021-07-13-assignment/)
    
- LIU MANYE
    - [Assignment write-up on Netlify](https://dataviz-lmy.netlify.app/posts/2021-07-13-visual-assignment/)
    
- LIU NIAN
    - [Assignment write-up on Netlify](https://visualisation-gallery-liunian.netlify.app/posts/2021-07-28-assignment/)
    
- LU DI
    - [Assignment write-up on Netlify](https://ludi1234.netlify.app/posts/2021-07-19-assignment/)
    
- MAO XIAOZHU
    - [Assignment write-up on Netlify](https://xiaozhumdataviz.netlify.app/posts/2021-07-03-assignmentmc1/)
    
- MIAO LU
    - [Assignment write-up on Netlify](https://miaolu-assign.netlify.app/posts/2021-07-25-assignment/)
    
- MISHRA AMRITA
    - [Assignment write-up on Netlify](https://amritamishradatablog.netlify.app/posts/2021-07-12-mini-challenge/)

- QIAN ZIWEI
    - [Assignment write-up on Netlify](https://qian-assignment.netlify.app/posts/2021-07-11-mini-challenge-3/)

- SNG KAH LEONG
    - [Assignment write-up on Netlify](https://beyourdetectiveassignment.netlify.app/)
    
- TANG HUINING
    - [Assignment write-up on Netlify](https://myhardwork.netlify.app/posts/2021-07-25-assignment/)
    
- TANG YUE
    - [Assignment write-up on Netlify](https://visualblog.netlify.app/posts/2021-07-26-assignmentvastchallenge2021/)
    
- VERTIKA PODDAR
    - [Assignment write-up on Netlify](https://vertika-assignment.netlify.app/overview.html)
    
- WANG JIAYI
    - [Assignment write-up on Netlify](https://datavisual-wjy.netlify.app/posts/2021-07-17-vast-challenge-2021/)
    
- WANG XIYU
    - [Assignment write-up on Netlify](https://isss608wangxiyu.netlify.app/posts/assignment/)
    
- YIN XIAOLAN
    - [Assignment write-up on Netlify](https://isss608xiaolanyin.netlify.app/posts/2021-07-07-assignment/)
    
- ZHANG XINRU
    - [Assignment write-up on Netlify](https://datavizblogzhangxinru.netlify.app/posts/2021-07-12-individual-assignment/)
    
- ZHANG YOUZHEN
    - [Assignment write-up on Netlify](https://dataviz-1.netlify.app/posts/2021-07-14-assignment/)
    
- ZHONG PING
    - [Assignment write-up on Netlify](https://zpmc2.netlify.app/)




