---
title: "Bullet Chart using bulletchartr"
author: "DR. Kam Tin Seong"
date: "3/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('tidyverse', 
             'bulletchartr')

for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

## Reading in CoffeeChain.rds

```{r}
coffeechain <- read_rds("data/CoffeeChain.rds")
```

```{r}
product <- coffeechain %>%
  group_by(`Product`) %>%
  summarise(`target` = sum(`Budget Sales`),
            `current` = sum(`Sales`)) %>%
  ungroup() 
```

```{r}
quali <- coffeechain %>%
  group_by(`Product`) %>%
  summarise(low = quantile(`Budget Sales`, probs = 0.50),
            medium = quantile(`Budget Sales`, probs = 0.95),
            high = quantile(`Budget Sales`, probs = 1.00))
```

```{r}
quali$low <- as.numeric(quali$low)
quali$medium <- as.numeric(quali$medium)
quali$high <- as.numeric(quali$high)
```

```{r}
dt <- left_join(product, quali) %>%
  mutate(info = "$") %>%
  rename(variable = "Product") %>%
  select(variable, info, current, low, medium, high, target)
```


This code chunk failed to work.

```{r eval=FALSE}
bullet_chart(dataframe = dt)
```